using System;
using System.Collections.Generic;

//THIS IS GENERATED BY OUR BUILD SCRIPT
namespace Elastic.Installer.Domain
{
	public static class ProductGuids
	{
		public static Guid ElasticsearchUpgradeCode => new Guid("daaa2cba-a1ed-4f29-afbf-5478617b00f6");
		public static Guid KibanaUpgradeCode => new Guid("6a2e6f51-5145-4c1a-8d05-2190ae213367");
		public static Dictionary<string, Guid> ElasticsearchProductCodes => new Dictionary<string, Guid>
		{
			{ "5.0.0-alpha1", new Guid("53e2a74c-26c1-4dd7-b6fb-4f91af321b28") },
			{ "5.0.0-alpha2", new Guid("a3be3c9c-00f0-4896-beb1-fea1c57bdd02") },
			{ "5.0.0-alpha3", new Guid("6035f515-1dfe-4a79-9ef5-7bb9384551b6") },
			{ "5.0.0-alpha4", new Guid("e979c387-45df-4bbb-aca5-82aec7b54f0e") },
			{ "5.0.0-alpha5", new Guid("c516704e-13ef-4ab8-9b27-c846d1e499b2") },
			{ "5.0.0-beta1", new Guid("498c0857-e6fc-48ec-b210-c70586861e49") },
			{ "5.0.0-rc1", new Guid("61847728-349e-4f2a-9965-cf8667d4558c") },
			{ "5.0.0", new Guid("cf632ca6-8588-4e94-9661-99cafcc974ac") },
			{ "5.0.1", new Guid("ab0244de-5a08-4812-97da-0c46c2f87eb9") },
			{ "5.0.2", new Guid("fbca0778-901d-4d2e-bf01-01001cc48e54") },
			{ "5.1.1", new Guid("82292245-25f0-41c1-88ee-0892b733a7e3") },
			{ "5.1.2", new Guid("21a99b00-bf06-4440-b35b-0d2e368089ae") },
			{ "5.2.0", new Guid("c7758e8d-5268-4baa-a6ae-58c8071725ec") },
			{ "5.2.1", new Guid("d8092759-699f-4889-9edf-92a96857125d") },
			{ "5.2.2", new Guid("6de3e5d5-bfe7-4422-bacf-ec2982d87122") },
			{ "5.3.0", new Guid("c954cde9-6960-49a9-a7b4-a065d498d037") },
			{ "5.3.1", new Guid("f508ab7b-066b-474f-aa0c-44d43c72d264") },
			{ "5.3.2", new Guid("8bc18570-a189-4304-8c85-1f2d7db3d839") },
			{ "5.4.0", new Guid("8279eff6-3a85-4b37-ac5a-3c5136bb5465") },
			{ "5.4.1", new Guid("127c0984-c0fe-4f6d-acf9-4c15101bd627") },
			{ "5.4.2", new Guid("13ad87cd-18f3-481e-a278-545d873f7353") },
			{ "5.4.3", new Guid("481906c0-70ca-4a4c-bb66-a6e25ed22b94") },
			{ "5.5.0", new Guid("344f09a4-5bf8-4d44-8e86-2130c263b08f") },
			{ "6.0.0-beta1", new Guid("f234f31d-f25c-4e64-8d3e-868f7b7ece97") }
		};

		public static Dictionary<string, Guid> KibanaProductCodes => new Dictionary<string, Guid>
		{
			{ "5.0.0-rc1", new Guid("23049947-d309-46f1-988b-49f62ed76630") },
			{ "5.0.0", new Guid("2136a182-7b96-42f3-b23a-42fead9e9b5d") },
			{ "5.0.1", new Guid("2c8d840a-f91b-4ecb-b66a-02e01ad649c1") },
			{ "5.0.2", new Guid("44c6b2cc-f1e0-4db1-8f25-8f0b3fde5d29") },
			{ "5.1.1", new Guid("059d0ca3-6448-4da3-97b6-83662aa754dc") },
			{ "5.1.2", new Guid("ad02e1c6-d675-48d1-8fbc-37270e3c0eab") },
			{ "5.2.0", new Guid("71281af0-9b66-4126-9172-63c9b45a0ef7") },
			{ "5.2.1", new Guid("6ae97b24-ff8a-4689-8257-3fc86b392f7d") },
			{ "5.2.2", new Guid("df74fae8-ad4f-4865-af61-d6ee4943d6b0") },
			{ "5.3.0", new Guid("e098f523-e2e9-436e-a3d8-6e72270305c4") },
			{ "5.3.1", new Guid("704b40e1-85b2-42d9-bff2-ad27838a24cb") },
			{ "5.3.2", new Guid("00001dc9-417b-48de-93a4-741dbf930b0b") },
			{ "5.4.0", new Guid("b6b05d55-e64e-4ed8-8faf-31518777f54d") },
			{ "5.4.1", new Guid("7441600b-2d85-4da6-8e49-a52aed0ca11f") },
			{ "5.5.0", new Guid("fe335f86-1cd3-42a5-905d-46af5eb5d267") }
		};

	}
}
