using System;
using System.Collections.Generic;

//THIS IS GENERATED BY OUR BUILD SCRIPT
namespace Elastic.Installer.Domain
{
	public static class ProductGuids
	{
		public static Guid ElasticsearchUpgradeCode => new Guid("daaa2cba-a1ed-4f29-afbf-5478617b00f6");
		public static Guid KibanaUpgradeCode => new Guid("6a2e6f51-5145-4c1a-8d05-2190ae213367");
		public static Dictionary<string, Guid> ElasticsearchProductCodes => new Dictionary<string, Guid>
		{
			{ "5.0.0-alpha1", new Guid("53e2a74c-26c1-4dd7-b6fb-4f91af321b28") },
			{ "5.0.0-alpha2", new Guid("a3be3c9c-00f0-4896-beb1-fea1c57bdd02") },
			{ "5.0.0-alpha3", new Guid("6035f515-1dfe-4a79-9ef5-7bb9384551b6") },
			{ "5.0.0-alpha4", new Guid("e979c387-45df-4bbb-aca5-82aec7b54f0e") },
			{ "5.0.0-alpha5", new Guid("c516704e-13ef-4ab8-9b27-c846d1e499b2") },
			{ "5.0.0-beta1", new Guid("498c0857-e6fc-48ec-b210-c70586861e49") },
			{ "5.0.0-rc1", new Guid("61847728-349e-4f2a-9965-cf8667d4558c") },
			{ "5.0.0", new Guid("cf632ca6-8588-4e94-9661-99cafcc974ac") },
			{ "5.0.1", new Guid("ab0244de-5a08-4812-97da-0c46c2f87eb9") },
			{ "5.0.2", new Guid("fbca0778-901d-4d2e-bf01-01001cc48e54") },
			{ "5.1.1", new Guid("82292245-25f0-41c1-88ee-0892b733a7e3") },
			{ "5.1.2", new Guid("21a99b00-bf06-4440-b35b-0d2e368089ae") },
			{ "5.2.0", new Guid("c7758e8d-5268-4baa-a6ae-58c8071725ec") },
			{ "5.2.1", new Guid("d8092759-699f-4889-9edf-92a96857125d") },
			{ "5.2.2", new Guid("6de3e5d5-bfe7-4422-bacf-ec2982d87122") },
			{ "5.3.0", new Guid("c954cde9-6960-49a9-a7b4-a065d498d037") },
			{ "5.3.1", new Guid("f508ab7b-066b-474f-aa0c-44d43c72d264") },
			{ "5.3.2", new Guid("8bc18570-a189-4304-8c85-1f2d7db3d839") },
			{ "5.4.0", new Guid("8279eff6-3a85-4b37-ac5a-3c5136bb5465") },
			{ "5.4.1", new Guid("127c0984-c0fe-4f6d-acf9-4c15101bd627") },
			{ "5.4.2", new Guid("13ad87cd-18f3-481e-a278-545d873f7353") },
			{ "5.4.3", new Guid("481906c0-70ca-4a4c-bb66-a6e25ed22b94") },
			{ "5.5.0", new Guid("344f09a4-5bf8-4d44-8e86-2130c263b08f") },
			{ "5.5.1", new Guid("2beb1fc0-042a-49fb-af3d-285a80f3c737") },
			{ "5.5.2", new Guid("2105d4cc-ac3e-4cf0-9214-fe4d9857f801") },
			{ "5.5.3", new Guid("1f75dce6-5c9e-43c4-ad23-72d94bfec22d") },
			{ "5.6.0", new Guid("72029505-94e9-4c29-a604-1da02d9d0402") },
			{ "5.6.1", new Guid("5e6f4d7a-9220-4432-9e5f-c9a9ab184dea") },
			{ "5.6.2", new Guid("650ba327-fac0-4276-a8c2-a3b5d458773c") },
			{ "5.6.3", new Guid("4f50ce6b-f115-46c3-8902-d915250c3370") },
			{ "5.6.4", new Guid("1a2e2c53-1753-4b63-98f8-013c3e67e223") },
			{ "5.6.5", new Guid("a8a40576-e918-4431-b4ee-a690882a35aa") },
			{ "5.6.6", new Guid("30dc148d-655e-4a0b-91a3-3f4d7b134a53") },
			{ "5.6.7", new Guid("05abedf2-1809-447f-9247-7736e8687fe9") },
			{ "5.6.8", new Guid("e2bb9379-a5bd-4710-a4fd-cbf28b94944a") },
			{ "5.6.9", new Guid("a3ad5bbc-30ee-4b91-ab1e-c75ca5f7f599") },
			{ "6.0.0-beta1", new Guid("f234f31d-f25c-4e64-8d3e-868f7b7ece97") },
			{ "6.0.0-beta2", new Guid("50f217e3-97b7-47ba-95f7-685f7db0c8aa") },
			{ "6.0.0-rc1", new Guid("23c31d4d-6990-4c2e-92c5-4dd3348d3e07") },
			{ "6.0.0-rc2", new Guid("576ef794-b3e3-4640-b717-1ed7d820d06e") },
			{ "6.0.0", new Guid("e962ab93-6e24-4128-bacb-93422cdcd50d") },
			{ "6.0.1", new Guid("0cf2db3b-dab9-4721-a5bb-e3b343ee02e1") },
			{ "6.0.2", new Guid("4379e718-4661-471b-9125-d83e2396f580") },
			{ "6.1.0", new Guid("7280a702-8532-4341-ac9e-38b221d14c1c") },
			{ "6.1.1", new Guid("0b5c8e9d-a23a-428e-a1bc-26924fced6b9") },
			{ "6.1.2", new Guid("e861bc6e-5eee-46e1-9bb5-73d70e3c1be8") },
			{ "6.1.3", new Guid("c850d041-38e2-4066-88bf-9386775802da") },
			{ "6.2.0", new Guid("bc4c5bb2-89a4-4958-a652-e0ff25b2df69") },
			{ "6.2.1", new Guid("bbb6bd0e-b892-4493-aab2-cac9c1ac73ae") },
			{ "6.2.2", new Guid("cb8b1af5-e480-4e68-8222-375a997fb64e") },
			{ "6.3.0", new Guid("183c1455-1bdf-4e9c-a07b-bfba13447735") },
			{ "6.3.1", new Guid("1c17c35c-b09f-4c5d-a271-0ba0f03d591f") },
			{ "6.3.2", new Guid("d0fc7098-4a42-479a-82de-e7f3966d11da") },
			{ "6.4.0", new Guid("3c08c055-faa4-4ab3-8adf-cef89a95fd5d") },
			{ "6.4.1", new Guid("57c3993a-ecd0-4f3f-bd52-51541591c78e") },
			{ "6.4.2", new Guid("8def2aae-cbe7-4db6-87d9-f95d5334dbf1") },
			{ "6.5.0", new Guid("bb1e8abb-36ba-4c27-9c7d-813a1d79bfd3") },
			{ "6.5.1", new Guid("2a3b25d6-d38b-4b34-b861-e5983f9a4f1b") },
			{ "6.5.2", new Guid("ab616add-f96b-4be9-af81-22ddb889e556") },
			{ "6.6.0", new Guid("7590b87f-1147-4c0b-b565-7dafc518ae7b") },
			{ "6.6.1", new Guid("d72b04b3-82ab-4819-8281-a56e30048df3") },
			{ "6.6.2", new Guid("b4053321-48a8-4112-8fcd-047d25c96962") },
			{ "6.7.0", new Guid("80e7847d-5153-48b0-a011-d1cae0983fa4") },
			{ "6.7.1", new Guid("73e22e50-daff-4a3d-bf31-829fd8c05694") },
			{ "6.7.2", new Guid("0b5a3943-37c7-47f3-af9d-16e7c93b5060") },
			{ "7.0.0-alpha1", new Guid("303b8268-6caa-4b82-aa3a-2b3e7197a0a3") }
		};

		public static Dictionary<string, Guid> KibanaProductCodes => new Dictionary<string, Guid>
		{
			{ "5.0.0-rc1", new Guid("23049947-d309-46f1-988b-49f62ed76630") },
			{ "5.0.0", new Guid("2136a182-7b96-42f3-b23a-42fead9e9b5d") },
			{ "5.0.1", new Guid("2c8d840a-f91b-4ecb-b66a-02e01ad649c1") },
			{ "5.0.2", new Guid("44c6b2cc-f1e0-4db1-8f25-8f0b3fde5d29") },
			{ "5.1.1", new Guid("059d0ca3-6448-4da3-97b6-83662aa754dc") },
			{ "5.1.2", new Guid("ad02e1c6-d675-48d1-8fbc-37270e3c0eab") },
			{ "5.2.0", new Guid("71281af0-9b66-4126-9172-63c9b45a0ef7") },
			{ "5.2.1", new Guid("6ae97b24-ff8a-4689-8257-3fc86b392f7d") },
			{ "5.2.2", new Guid("df74fae8-ad4f-4865-af61-d6ee4943d6b0") },
			{ "5.3.0", new Guid("e098f523-e2e9-436e-a3d8-6e72270305c4") },
			{ "5.3.1", new Guid("704b40e1-85b2-42d9-bff2-ad27838a24cb") },
			{ "5.3.2", new Guid("00001dc9-417b-48de-93a4-741dbf930b0b") },
			{ "5.4.0", new Guid("b6b05d55-e64e-4ed8-8faf-31518777f54d") },
			{ "5.4.1", new Guid("7441600b-2d85-4da6-8e49-a52aed0ca11f") },
			{ "5.5.0", new Guid("fe335f86-1cd3-42a5-905d-46af5eb5d267") },
			{ "5.5.1", new Guid("44f33065-4532-4aee-9bbb-e681c32845ef") },
			{ "5.5.2", new Guid("fc7519ca-27ee-416e-bb6d-37bfe3218b99") },
			{ "5.5.3", new Guid("d968c8bd-2388-4103-bd58-4966c2338718") },
			{ "5.6.0", new Guid("c3409b89-7793-4231-942c-6c998523d08f") },
			{ "6.0.0-beta1", new Guid("b9d8d2c7-9e73-4936-ac76-1626dc25d7b9") },
			{ "6.0.0-beta2", new Guid("da8a7f2e-077f-493d-8986-b02656489b90") }
		};

	}
}
