using System;
using System.Collections.Generic;

//THIS IS GENERATED BY OUR BUILD SCRIPT
namespace Elastic.Installer.Domain
{
	public static class ProductGuids
	{
		public static Guid ElasticsearchUpgradeCode => new Guid("daaa2cba-a1ed-4f29-afbf-5478617b00f6");
		public static Guid KibanaUpgradeCode => new Guid("6a2e6f51-5145-4c1a-8d05-2190ae213367");
		public static Dictionary<string, Guid> ElasticsearchProductCodes => new Dictionary<string, Guid>
		{
			{ "5.0.0-alpha1", new Guid("53e2a74c-26c1-4dd7-b6fb-4f91af321b28") },
			{ "5.0.0-alpha2", new Guid("a3be3c9c-00f0-4896-beb1-fea1c57bdd02") },
			{ "5.0.0-alpha3", new Guid("6035f515-1dfe-4a79-9ef5-7bb9384551b6") },
			{ "5.0.0-alpha4", new Guid("e979c387-45df-4bbb-aca5-82aec7b54f0e") },
			{ "5.0.0-alpha5", new Guid("c516704e-13ef-4ab8-9b27-c846d1e499b2") },
			{ "5.0.0-beta1", new Guid("498c0857-e6fc-48ec-b210-c70586861e49") },
			{ "5.0.0-rc1", new Guid("61847728-349e-4f2a-9965-cf8667d4558c") },
			{ "5.0.0", new Guid("cf632ca6-8588-4e94-9661-99cafcc974ac") },
			{ "5.0.1", new Guid("ab0244de-5a08-4812-97da-0c46c2f87eb9") },
			{ "5.1.1", new Guid("82292245-25f0-41c1-88ee-0892b733a7e3") },
			{ "5.1.2", new Guid("d83a7f89-812f-4c05-9849-82a894696fed") }
		};

		public static Dictionary<string, Guid> KibanaProductCodes => new Dictionary<string, Guid>
		{
			{ "5.0.0-rc1", new Guid("23049947-d309-46f1-988b-49f62ed76630") },
			{ "5.0.0", new Guid("2136a182-7b96-42f3-b23a-42fead9e9b5d") },
			{ "5.0.1", new Guid("2c8d840a-f91b-4ecb-b66a-02e01ad649c1") },
			{ "5.1.1", new Guid("059d0ca3-6448-4da3-97b6-83662aa754dc") },
			{ "5.1.2", new Guid("03667a3a-5a75-4f20-8182-95c224ea39da") }
		};

	}
}
