// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Elasticsearch, you know for search!")]
[assembly: AssemblyDescriptionAttribute("Elasticsearch is a distributed, RESTful search and analytics engine capable of solving a growing number of use cases. As the heart of the Elastic Stack, it centrally stores your data so you can discover the expected and uncover the unexpected.")]
[assembly: GuidAttribute("d4fb307f-cb1d-4026-bd28-ca1d0016d709")]
[assembly: AssemblyProductAttribute("Elasticsearch")]
[assembly: AssemblyMetadataAttribute("GitBuildHash","764ecb")]
[assembly: AssemblyCompanyAttribute("Elasticsearch BV")]
[assembly: AssemblyCopyrightAttribute("Apache License, version 2 (ALv2). Copyright Elasticsearch.")]
[assembly: AssemblyTrademarkAttribute("Elasticsearch is a trademark of Elasticsearch BV, registered in the U.S. and in other countries.")]
[assembly: AssemblyVersionAttribute("5.4.3")]
[assembly: AssemblyFileVersionAttribute("5.4.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Elasticsearch, you know for search!";
        internal const System.String AssemblyDescription = "Elasticsearch is a distributed, RESTful search and analytics engine capable of solving a growing number of use cases. As the heart of the Elastic Stack, it centrally stores your data so you can discover the expected and uncover the unexpected.";
        internal const System.String Guid = "d4fb307f-cb1d-4026-bd28-ca1d0016d709";
        internal const System.String AssemblyProduct = "Elasticsearch";
        internal const System.String AssemblyMetadata_GitBuildHash = "764ecb";
        internal const System.String AssemblyCompany = "Elasticsearch BV";
        internal const System.String AssemblyCopyright = "Apache License, version 2 (ALv2). Copyright Elasticsearch.";
        internal const System.String AssemblyTrademark = "Elasticsearch is a trademark of Elasticsearch BV, registered in the U.S. and in other countries.";
        internal const System.String AssemblyVersion = "5.4.3";
        internal const System.String AssemblyFileVersion = "5.4.3";
    }
}
